applications/concept-cat/src/main/java/no/ccat/service/RDFToModelTransformer.java, applications/concept-cat/src/test/resources/ConceptCatalogueHarvest.turtle
Med mye knoting og god hjelp fra Alex lagres nå 'sources' i elasticsearch
=> Fixed extraction of definition

src/main/java/no/ccat/service/ConceptDenormalizedRepository.java, src/main/java/no/ccat/service/RDFToModelTransformer.java, src/main/resources/application.yml
=> fix: #2489

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQConfig.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQListener.kt, src/main/resources/application.yml
=> chore: add rabbit-listener

src/main/kotlin/no/fdk/fdk_concept_harvester/controller/CollectionsController.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/controller/ConceptsController.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rdf/RDFUtils.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/contract/CollectionsTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/contract/ConceptTest.kt
=> chore: support rdf-serializations TRIG, TRIX & N-QUADS

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQPublisher.kt
resolve https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/447
=> new rabbit message

src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/HarvestAdminAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterActivity.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/HarvestAdmin.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQListener.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/fdk_concept_harvester/service/HarvestAdminAdapter.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/ContractMock.kt
=> chore: use new harvest-admin

src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/ConceptsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/DefaultOrganizationsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/OrganizationsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvestHelpers.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/AuthHeader.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/ContentType.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/HarvestAdmin.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/tbx/TbxUtils.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/tbx/TbxTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/TestOrganizationsAdapter.kt, src/test/resources/tbx.ttl, src/test/resources/tbx.xml, src/test/resources/tbx_no_publisher.ttl, src/test/resources/tbx_no_publisher.xml
Fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/545
=> feat: add TBX support

src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/ConceptsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterActivity.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/HarvestAdmin.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/HarvestReport.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/UpdateSearchMessage.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQPublisher.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rdf/RDFUtils.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/tbx/TbxUtils.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/TestData.kt
=> feat: harvest reports

src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/ConceptsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rdf/RDFUtils.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/tbx/TbxUtils.kt
fixes https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/575
=> chore: rm unnecessary error logs

src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterActivity.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/HarvestAdmin.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/RabbitHarvestTrigger.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/rabbit/RabbitMQListener.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/service/HarvestAdminAdapter.kt
=> chore: add forceUpdate to incoming rabbit messages

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/Application.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/configuration/SecurityConfig.kt
https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/598
=> chore: update deprecated security config

src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvestHelpers.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/service/UpdateService.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt, src/test/resources/empty_generated_collection.ttl
=> chore: always update generated collections

src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt
=> chore: do not update modified on forced update

src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvestHelpers.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt, src/test/resources/harvest_response_empty.ttl
part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/815
=> fix: allow empty collections

.github/workflows/deploy-prod&demo.yaml, .github/workflows/deploy-staging.yaml, deploy/base/fdk-concept-harvester-deployment.yaml, deploy/base/fdk-concept-harvester-service.yaml, deploy/base/kustomization.yaml, deploy/demo/env.yaml, deploy/demo/kustomization.yaml, deploy/prod/env.yaml, deploy/prod/kustomization.yaml, deploy/staging/env.yaml, deploy/staging/kustomization.yaml
=> feat: add deploy with kustomize

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvesterTest.kt
part of https://github.com/Informasjonsforvaltning/fdk-issue-tracker/issues/932
=> fix: save concepts when republished with no changes

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/configuration/SecurityConfig.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/controller/ConceptsController.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/HarvestHelpers.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/repository/ConceptMetaRepository.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/service/ConceptService.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/contract/ConceptTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/service/ConceptServiceTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/TestUtils.kt
=> feat: remove concept

pom.xml, src/main/kotlin/no/fdk/fdk_concept_harvester/adapter/ConceptsAdapter.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/controller/ConceptsController.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/harvester/ConceptHarvester.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/model/DuplicateIRI.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/service/ConceptService.kt, src/main/resources/application.yml, src/test/kotlin/no/fdk/fdk_concept_harvester/contract/ConceptTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/service/ConceptServiceTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/TestUtils.kt
=> feat: remove duplicates

src/main/kotlin/no/fdk/fdk_concept_harvester/controller/ConceptsController.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/service/ConceptService.kt, src/main/kotlin/no/fdk/fdk_concept_harvester/service/TurtleService.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/contract/ConceptTest.kt, src/test/kotlin/no/fdk/fdk_concept_harvester/utils/DatabaseData.kt
=> feat: purge turtle files by fdkID

.github/workflows/deploy-prod&demo.yaml, .github/workflows/deploy-staging.yaml, Dockerfile, deploy/base/kustomization.yaml, deploy/demo/env.yaml, deploy/prod/env.yaml, deploy/staging/env.yaml, src/main/kotlin/no/fdk/fdk_concept_harvester/configuration/SecurityConfig.kt, src/main/resources/application.yml
resolve https://github.com/Informasjonsforvaltning/fdk-team-private/issues/116
=> chore: cors config
